version: '3.8'

# Docker Compose configuration for building from source
# Use this if you want to build the image locally instead of using the pre-built one

services:
  monica-file-processor:
    build: 
      context: .
      args:
        GITHUB_BRANCH: ${GITHUB_BRANCH:-main}
    container_name: monica-file-processor-build
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/data
    volumes:
      - monica_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  monica_data:
    driver: local